/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package castracker;

import javax.swing.*;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author SangHooLeeINtern
 */
public class LogInPage extends javax.swing.JFrame {

    Statement stmt;
    ResultSet rs;
    public static Connection con;
    int curRow = 0;
    CallableStatement cs;
    JFrame mf = new MainFrame();
    
    //JFrame vf - new ViewFrame();
    /**
     * Creates new form MainPage
     */
    public LogInPage() {
        initComponents();

        try {
            Connection con;
            String host = "jdbc:sqlserver://localhost:1433;databaseName=master;integratedSecurity = true";
            con = DriverManager.getConnection(host);
            stmt = con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);

            rs = stmt.executeQuery("Select * from dbo.CAStable");
            rs.next();
            //JOptionPane.showMessageDialog(MainPage.this, "Connection Successful");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error 2: " + ex.getMessage());
            System.exit(0);
        }
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEnterData = new javax.swing.JButton();
        lblID = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        lblLastName = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        lblFistName = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(200, 200, 0, 0));

        btnEnterData.setText("Enter Data");
        btnEnterData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnterDataActionPerformed(evt);
            }
        });

        lblID.setText("ID:");

        lblLastName.setText("Last Name:");

        lblFistName.setText("First Name:");

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(79, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblFistName)
                    .addComponent(lblLastName)
                    .addComponent(lblID))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtID, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                        .addComponent(btnEnterData)
                        .addComponent(txtLastName)
                        .addComponent(txtFirstName))
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(111, 111, 111))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(81, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFistName)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLastName)
                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblID)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addComponent(btnEnterData)
                .addGap(18, 18, 18)
                .addComponent(btnBack)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnterDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnterDataActionPerformed
        MainFrame maf = new MainFrame();
        if (!txtID.getText().isEmpty()) {
            try {
                Connection con;
                String host = "jdbc:sqlserver://localhost:1433;databaseName=master;integratedSecurity = true";
                con = DriverManager.getConnection(host);
                stmt = con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
                rs = stmt.executeQuery("Select lastName, firstName, ID From dbo.CASpasswordID where ID ='"+ txtID.getText()+"'");
                rs.next();
                
                String lName = rs.getString("lastName");
                String fName = rs.getString("firstName");
                String sID = rs.getString("ID");
                lName = lName.trim();
                fName = fName.trim();
                sID = sID.trim();
                if(lName.equals(txtLastName.getText()) && fName.equals(txtFirstName.getText()) && sID.equals(txtID.getText())){
                    MainFrame.lblLastName.setText(lName);
                    MainFrame.lblFirstName.setText(fName);
                    MainFrame.lblID.setText(sID);
                    this.dispose();
                    mf.setVisible(true);
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this,"error 2 "+ ex.getMessage());
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                
            //StudentSetUp ssu = new StudentSetUp();
                //ssu.setVisible(true);
            }
        }
    }//GEN-LAST:event_btnEnterDataActionPerformed
    
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        this.dispose();
        JFrame frame = new MainPage();
        frame.setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed
    
    /**
         * @param args the command line arguments
         */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnEnterData;
    private javax.swing.JLabel lblFistName;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtLastName;
    // End of variables declaration//GEN-END:variables
}
