/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package castracker;

import javax.swing.*;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.DocumentFilter;
import javax.swing.text.PlainDocument;
import java.awt.*;
import java.sql.*;

/**
 *
 * @author Sang-Hoo
 */
public class MainFrame extends javax.swing.JFrame {

    Statement stmt;
    ResultSet rs;
    int curRow = 0;
    int i = 0;
    CallableStatement cs;
    public static JLabel lblLastName = new JLabel();
    public static JLabel lblFirstName = new JLabel();
    public static JLabel lblID = new JLabel();

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        lblWarn1.setVisible(false);
        lblWarn2.setVisible(false);
        lblWarn3.setVisible(false);
        lblWarn4.setVisible(false);
        MainFrame.MyDocFilter myFilter = new MainFrame.MyDocFilter();

        ((PlainDocument) this.txtTime.getDocument()).setDocumentFilter(myFilter);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanel1 = new javax.swing.JPanel();
        btnDate = new javax.swing.JButton();
        txtProjectName = new javax.swing.JTextField();
        lblProjectName = new javax.swing.JLabel();
        cbbObjectives = new javax.swing.JComboBox();
        lblTime = new javax.swing.JLabel();
        lblReflection = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblWarn1 = new javax.swing.JLabel();
        lblWarn3 = new javax.swing.JLabel();
        lblWarn4 = new javax.swing.JLabel();
        lblWarn2 = new javax.swing.JLabel();
        cboCreativity = new javax.swing.JCheckBox();
        cboAction = new javax.swing.JCheckBox();
        cboService = new javax.swing.JCheckBox();
        lblDate = new javax.swing.JLabel();
        txtTime = new javax.swing.JTextField();
        btnDate1 = new javax.swing.JButton();
        lblDate1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtReflection = new javax.swing.JTextArea();
        btnLogOut = new javax.swing.JButton();
        ImageIcon image = new ImageIcon("Image/IB Logo.png");
        jLabel2 = new JLabel(image);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(200, 200, 0, 0));

        btnDate.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btnDate.setText("End Date");
        btnDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDateActionPerformed(evt);
            }
        });

        txtProjectName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProjectNameActionPerformed(evt);
            }
        });

        lblProjectName.setText("Activity Name");

        cbbObjectives.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cbbObjectives.setMaximumRowCount(9);
        cbbObjectives.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Objective", "Increased their awareness of their own strength", "Undertaken new challenges", "Planned and initiated activities", "Worked collaboratively with others", "Shown perseverance and commitment in their activities", "Engaged with issues of global importance", "Considered the ethical implication of their action", "Developed new skill" }));
        cbbObjectives.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbObjectivesActionPerformed(evt);
            }
        });

        lblTime.setText("Total Time(in hour)");

        lblReflection.setText("Reflection");

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        jLabel1.setText("Made by Sang Hoo Lee ");

        lblWarn1.setForeground(new java.awt.Color(255, 0, 51));
        lblWarn1.setText("*Enter Activity Name");

        lblWarn3.setForeground(new java.awt.Color(255, 0, 51));
        lblWarn3.setText("*Enter Reflection");

        lblWarn4.setForeground(new java.awt.Color(255, 0, 51));
        lblWarn4.setText("*Enter Date");

        lblWarn2.setForeground(new java.awt.Color(255, 0, 51));
        lblWarn2.setText("*Enter Time");

        cboCreativity.setText("Creativity");
        cboCreativity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboCreativityActionPerformed(evt);
            }
        });

        cboAction.setText("Action");

        cboService.setText("Service");

        lblDate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimeActionPerformed(evt);
            }
        });

        btnDate1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btnDate1.setText("Start Date");
        btnDate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDate1ActionPerformed(evt);
            }
        });

        lblDate1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtReflection.setColumns(20);
        txtReflection.setRows(5);
        jScrollPane1.setViewportView(txtReflection);

        btnLogOut.setText("Log out");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/castracker/IB Logo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDate1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblDate, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtProjectName, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblWarn3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnLogOut)
                                    .addComponent(jLabel2))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(101, 101, 101)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(188, 188, 188)
                                        .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(lblReflection)
                                                .addGap(89, 89, 89))
                                            .addComponent(cbbObjectives, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(44, 44, 44)
                                                .addComponent(cboCreativity, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(61, 61, 61))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(btnDate1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(50, 50, 50)))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblWarn4)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(cboAction)
                                                .addGap(88, 88, 88)
                                                .addComponent(cboService)))))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblTime)
                                        .addGap(26, 26, 26)
                                        .addComponent(lblWarn2))
                                    .addComponent(txtTime, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(294, 294, 294)
                                .addComponent(btnDate, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(136, 136, 136)
                                .addComponent(lblProjectName)
                                .addGap(27, 27, 27)
                                .addComponent(lblWarn1)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblProjectName)
                            .addComponent(btnDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblWarn1)
                            .addComponent(btnDate1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblWarn4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtProjectName, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(lblDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblDate1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cboCreativity, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cboAction)
                                .addComponent(cboService)))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTime)
                            .addComponent(lblWarn2))
                        .addGap(32, 32, 32)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbbObjectives)
                    .addComponent(txtTime))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblReflection)
                            .addComponent(lblWarn3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(btnLogOut)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jLayeredPane1.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jPanel1.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDateActionPerformed
        // TODO add your handling code here:
        JPanel DatePicker = new DatePicker(this, lblDate);
        jLayeredPane1.add(DatePicker);
        DatePicker.setOpaque(true);
        jPanel1.setOpaque(false);
        DatePicker.setVisible(true);
        jLayeredPane1.moveToFront(DatePicker);
        //jLayeredPane1.moveToBack(jPanel1);
        for (Component c : jPanel1.getComponents()) {
            c.setEnabled(false);
            txtTime.setEnabled(false);
        }


    }//GEN-LAST:event_btnDateActionPerformed
    private void checkTextIsEmpty() {

        if (lblDate.getText().isEmpty() || lblDate1.getText().isEmpty()) {
            lblWarn4.setVisible(true);
        } else {
            lblWarn4.setVisible(false);
        }

        if (txtProjectName.getText().isEmpty()) {
            lblWarn1.setVisible(true);
        } else {
            lblWarn1.setVisible(false);
        }

        if (txtTime.getText().isEmpty()) {
            lblWarn2.setVisible(true);
        } else {
            lblWarn2.setVisible(false);
        }
        if (txtReflection.getText().isEmpty()) {
            lblWarn3.setVisible(true);
        } else {
            lblWarn3.setVisible(false);
        }
    }

    private boolean isTextEmpty() {

        if (lblDate.getText().isEmpty() || lblDate1.getText().isEmpty()) {
            return false;
        } else if (!lblDate.getText().isEmpty() && !lblDate1.getText().isEmpty()) {
            return true;
        } else if (txtProjectName.getText().isEmpty()) {
            return false;
        } else if (!txtProjectName.getText().isEmpty()) {
            return true;
        } else if (txtTime.getText().isEmpty()) {
            return false;
        } else if (!txtTime.getText().isEmpty()) {
            return true;
        } else if (txtReflection.getText().isEmpty()) {
            return false;
        } else if (!txtReflection.getText().isEmpty()) {
            return true;
        } else {
            return true;
        }

    }

    private void txtProjectNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProjectNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProjectNameActionPerformed

    private void cbbObjectivesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbObjectivesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbObjectivesActionPerformed

    @SuppressWarnings("empty-statement")
    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        this.checkTextIsEmpty();
        System.out.println(btnLogOut.getBounds());
        if (isTextEmpty() && !cbbObjectives.getSelectedItem().toString().equals("Objective") && (cboCreativity.isSelected()
                || cboAction.isSelected() || cboService.isSelected())) {
            System.out.println(lblLastName.getText() + ", " + lblFirstName.getText());

            try {
                Connection con;
                String host = "jdbc:sqlserver://localhost:1433;databaseName=master;integratedSecurity = true";
                con = DriverManager.getConnection(host);
                stmt = con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);

                /**
                 * execute a query where you can get the specific record for the
                 * studentID. Once you have the record you must put it into
                 * storage variables Now update each storage variable with the
                 * new information You will have to concatenate the new data
                 * with the old data. Therefore: if no record exists for the
                 * specified studentID then simply update the information with
                 * the new. If the record exists add each new element to each
                 * old element and update the information.
                 */
                rs = stmt.executeQuery("SELECT COUNT (*) FROM dbo.CAStable WHERE studentID = '" + lblID.getText() + "'");
                rs.next();
                cs = con.prepareCall("{call setStudentInfo(?,?,?,?,?,?,?,?,?,?,?,?)}");
                String b = lblLastName.getText();
                cs.setString(1, b);
                String l = lblFirstName.getText();
                cs.setString(2, l);
                cs.setString(3, lblDate1.getText());
                cs.setString(4, lblDate.getText());
                cs.setString(5, txtProjectName.getText());

                if (cboCreativity.isSelected()) {
                    cs.setInt(6, 1);
                } else {
                    cs.setInt(6, 0);
                }
                if (cboAction.isSelected()) {
                    cs.setInt(7, 1);
                } else {
                    cs.setInt(7, 0);
                }
                if (cboService.isSelected()) {
                    cs.setInt(8, 1);
                } else {
                    cs.setInt(8, 0);
                }
                cs.setString(9, cbbObjectives.getSelectedItem().toString());
                String j = txtTime.getText();
                int k = Integer.parseInt(j);
                String time = k + "hours";
                cs.setString(10, time);
                cs.setString(11, txtReflection.getText());
                String m = lblID.getText();
                cs.setString(12, m);
                cs.executeUpdate();
                JOptionPane.showMessageDialog(this, "Data Entered");
                //}
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Error 1: ");
                System.exit(0);
            }

        }
    }//GEN-LAST:event_btnSubmitActionPerformed
    private class MyDocFilter extends DocumentFilter {

        @Override
        public void insertString(DocumentFilter.FilterBypass fb, int offset,
                String text, AttributeSet attr) throws BadLocationException {
            for (char c : text.toCharArray()) {
                if (!Character.isDigit(c)) {
                    return;
                }
            }
            fb.insertString(offset, text.toUpperCase(), attr);
        }

        @Override
        public void replace(DocumentFilter.FilterBypass fb, int offset,
                int length, String text, AttributeSet attrs)
                throws BadLocationException {
            for (char c : text.toCharArray()) {
                if (!Character.isDigit(c)) {
                    return;
                }
            }
            fb.replace(offset, length, text.toUpperCase(), attrs);
        }
    }
    private void cboCreativityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboCreativityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboCreativityActionPerformed

    private void txtTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimeActionPerformed

    private void btnDate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDate1ActionPerformed
        // TODO add your handling code here:
        JPanel DatePicker = new DatePicker(this, lblDate1);
        jLayeredPane1.add(DatePicker);
        DatePicker.setOpaque(true);
        jPanel1.setOpaque(false);
        DatePicker.setVisible(true);
        jLayeredPane1.moveToFront(DatePicker);
        //jLayeredPane1.moveToBack(jPanel1);
        for (Component c : jPanel1.getComponents()) {
            c.setEnabled(false);
            txtTime.setEnabled(false);
        }
    }//GEN-LAST:event_btnDate1ActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        // TODO add your handling code here:
        this.dispose();
        JFrame lip = new LogInPage();
        lip.setVisible(true);
    }//GEN-LAST:event_btnLogOutActionPerformed
    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDate;
    private javax.swing.JButton btnDate1;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox cbbObjectives;
    private javax.swing.JCheckBox cboAction;
    private javax.swing.JCheckBox cboCreativity;
    private javax.swing.JCheckBox cboService;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JLayeredPane jLayeredPane1;
    public javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel lblDate;
    public javax.swing.JLabel lblDate1;
    private javax.swing.JLabel lblProjectName;
    private javax.swing.JLabel lblReflection;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblWarn1;
    private javax.swing.JLabel lblWarn2;
    private javax.swing.JLabel lblWarn3;
    private javax.swing.JLabel lblWarn4;
    private javax.swing.JTextField txtProjectName;
    private javax.swing.JTextArea txtReflection;
    public javax.swing.JTextField txtTime;
    // End of variables declaration//GEN-END:variables
}
