/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package castracker;

import javax.swing.*;
import java.sql.*;

/**
 *
 * @author SangHooLeeINtern
 */
public class MainPage extends javax.swing.JFrame {
    Statement stmt;
    ResultSet rs;
    Connection con;
    int curRow = 0;
    CallableStatement cs;
    

    /**
     * Creates new form MainPage
     */
    public MainPage() {
        
        initComponents();
        optionPanel.setVisible(true);

        
        
            try {
                Connection con;
                String host = "jdbc:sqlserver://localhost:1433;databaseName=master;integratedSecurity = true";
                con = DriverManager.getConnection(host);
                stmt = con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);

                rs = stmt.executeQuery("Select * from dbo.CASTable");
                rs.next();
                //JOptionPane.showMessageDialog(MainPage.this, "Connection Successful");
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(MainPage.this,"error 3 ");
            }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        optionPanel = new javax.swing.JPanel();
        btnEnterData = new javax.swing.JButton();
        btnViewData = new javax.swing.JButton();
        btnStudnetSetup = new javax.swing.JButton();
        ImageIcon image = new ImageIcon("Image/IB Logo BIG.png");
        jLabel1 = new JLabel(image);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student CAS Hours tracker");
        setBounds(new java.awt.Rectangle(200, 200, 0, 0));

        btnEnterData.setText("Enter Data");
        btnEnterData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnterDataActionPerformed(evt);
            }
        });

        btnViewData.setText("View Data");
        btnViewData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDataActionPerformed(evt);
            }
        });

        btnStudnetSetup.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btnStudnetSetup.setText("Enter Student");
        btnStudnetSetup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudnetSetupActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/castracker/IB Logo BIG.png"))); // NOI18N

        javax.swing.GroupLayout optionPanelLayout = new javax.swing.GroupLayout(optionPanel);
        optionPanel.setLayout(optionPanelLayout);
        optionPanelLayout.setHorizontalGroup(
            optionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, optionPanelLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE)
                .addGroup(optionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnViewData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEnterData, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                    .addComponent(btnStudnetSetup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(66, 66, 66))
        );
        optionPanelLayout.setVerticalGroup(
            optionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, optionPanelLayout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addGroup(optionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(optionPanelLayout.createSequentialGroup()
                        .addComponent(btnEnterData)
                        .addGap(18, 18, 18)
                        .addComponent(btnViewData)
                        .addGap(18, 18, 18)
                        .addComponent(btnStudnetSetup))
                    .addComponent(jLabel1))
                .addGap(84, 84, 84))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(optionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(optionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnterDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnterDataActionPerformed
        // TODO add your handling code here:
        
        this.dispose();
        JFrame log = new LogInPage();
        log.setVisible(true);
        
        
    }//GEN-LAST:event_btnEnterDataActionPerformed

    private void btnViewDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDataActionPerformed
        this.setVisible(false);
        JFrame vframe = new viewFrame();
        vframe.setVisible(true);
        
    }//GEN-LAST:event_btnViewDataActionPerformed

    private void btnStudnetSetupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudnetSetupActionPerformed
        // TODO add your handling code here:
        this.dispose();
        JFrame ssu = new enterStudentLoginFrame();
        ssu.setVisible(true);
    }//GEN-LAST:event_btnStudnetSetupActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnterData;
    private javax.swing.JButton btnStudnetSetup;
    private javax.swing.JButton btnViewData;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel optionPanel;
    // End of variables declaration//GEN-END:variables
}
