/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package castracker;

import javax.swing.*;
import java.awt.*;
import java.io.IOException;
import java.sql.*;

/**
 *
 * @author DavidE
 */
public class viewStudentFrame extends javax.swing.JFrame {

    Connection con;
    ResultSet rs;
    Statement stmt;
    CallableStatement cs;
    
    
   
    
    
    
    
    /**
     * Creates new form viewStudentFrame
     */
    public viewStudentFrame() {
        initComponents();
        for (Component c : viewPanel.getComponents()) {
            c.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtSummary = new javax.swing.JTextArea();
        btnBack = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnPrevious = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        searchPanel = new javax.swing.JPanel();
        txtStudentID = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstResults = new javax.swing.JList();
        btnSelect = new javax.swing.JButton();
        btnGoBack = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(200, 200, 0, 0));

        txtSummary.setEditable(false);
        txtSummary.setColumns(20);
        txtSummary.setRows(5);
        jScrollPane1.setViewportView(txtSummary);

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel3.setText("Made by David Edwards");

        btnPrevious.setText("Previous");
        btnPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviousActionPerformed(evt);
            }
        });

        btnNext.setText("Next");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout viewPanelLayout = new javax.swing.GroupLayout(viewPanel);
        viewPanel.setLayout(viewPanelLayout);
        viewPanelLayout.setHorizontalGroup(
            viewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewPanelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(viewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(viewPanelLayout.createSequentialGroup()
                        .addComponent(btnPrevious)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38))
                    .addGroup(viewPanelLayout.createSequentialGroup()
                        .addGroup(viewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        viewPanelLayout.setVerticalGroup(
            viewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(viewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnBack)
                    .addComponent(btnNext)
                    .addComponent(btnPrevious))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setText("Student ID:");

        jLabel2.setText("Last Name:");

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(lstResults);

        btnSelect.setText("Select");
        btnSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectActionPerformed(evt);
            }
        });

        btnGoBack.setText("Back");
        btnGoBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoBackActionPerformed(evt);
            }
        });

        jLabel4.setText("Search for Student");

        javax.swing.GroupLayout searchPanelLayout = new javax.swing.GroupLayout(searchPanel);
        searchPanel.setLayout(searchPanelLayout);
        searchPanelLayout.setHorizontalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchPanelLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                    .addGroup(searchPanelLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtStudentID, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(searchPanelLayout.createSequentialGroup()
                        .addComponent(btnSearch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnGoBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSelect)
                .addGap(147, 147, 147))
        );
        searchPanelLayout.setVerticalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtStudentID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(btnSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSelect)
                    .addComponent(btnGoBack))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(viewPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(9, 9, 9)
                    .addComponent(viewPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(18, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here: select * from dbo.something where 
        String studentID = txtStudentID.getText();
        String lastNameyeah = txtLastName.getText();  
        try {
            String host = "jdbc:sqlserver://localhost:1433;databaseName=master;integratedSecurity = true";
            con = DriverManager.getConnection(host);
            stmt = con.createStatement();
            rs = stmt.executeQuery("Select * from dbo.CASpasswordID where lastName = '" +
                    lastNameyeah + "' and ID = '" + studentID + "'");
            
            
            
            DefaultListModel table = new DefaultListModel();
            while (rs.next()) {
                String output = rs.getString("firstName").trim() + " " + rs.getString("lastName").trim() + "  ID: " + rs.getString("ID").trim();
                table.addElement(output);
            }
            lstResults.setModel(table);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this,"error 5 "+ ex.getMessage());
        }
        
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectActionPerformed
        // TODO add your handling code here:
        try {
            String name1 = txtStudentID.getText();
            String name2 = txtLastName.getText();
            stmt = con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_READ_ONLY);
            rs = stmt.executeQuery("Select * from dbo.CASTable where lastName = '" + txtLastName.getText() + "' and studentID = '" + txtStudentID.getText() + "'");
            rs.next();
            
            //lblNameStudent.setText(name1 + " " + name2);
            
            String reflection = rs.getString("reflection").trim();
            
            String fName = rs.getString("firstName");
            String lName = rs.getString("lastName");
            String startDate = rs.getString("startDate");
            String endDate = rs.getString("endDate");
            String pName = rs.getString("projectName");
            int creativity = rs.getInt("creativity");
            int action = (rs.getInt("action"));
            int service = (rs.getInt("service"));
            String objective = rs.getString("objective");
            String hours = rs.getString("hours");
            String id = rs.getString("studentID");
            
            String firstName = fName.trim();
            String lastName = lName.trim();
            String newID = id.trim();
            String newCreativity;
            String newAction;
            String newService;
            if (creativity == 0)
                newCreativity = "no";
            else
                newCreativity = "yes";
            if (action == 0)
                newAction = "no";
            else
                newAction = "yes";
            if (service == 0) 
                newService = "no";
            else 
                newService = "yes";
            
            
            String println = "Name: " + firstName + " " + lastName + "\n" +
                    "ID: " + newID + "\n" +
                    "Start date: " + startDate + "\n" + 
                    "End date: " + endDate + "\n" + 
                    "Project Name: " + pName + "\n" +
                    "creativity: " + newCreativity + "\n" +
                    "Action: " + newAction + "\n" +
                    "Service: " + newService + "\n" +
                    "Objective: " + objective + "\n" +
                    "Hours: " + hours + "\n" +
                    "Reflection: " + reflection + "\n";
            
            
            
            
            txtSummary.setText(println);
            viewPanel.setVisible(true);
            searchPanel.setVisible(false);
            
//            viewPanel.setVisible(false);
//            infoPanel.setVisible(true);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
        for (Component c : viewPanel.getComponents()) {
            c.setEnabled(true);
        }for (Component c : searchPanel.getComponents()) {
            c.setEnabled(false);
        }
    }//GEN-LAST:event_btnSelectActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        viewPanel.setVisible(false);
        searchPanel.setVisible(true);
        for (Component c : viewPanel.getComponents()) {
            c.setEnabled(false);
        }for (Component c : searchPanel.getComponents()) {
            c.setEnabled(true);
        }
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnGoBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoBackActionPerformed
        // TODO add your handling code here:
        this.dispose();
        JFrame mpage = new MainPage();
        mpage.setVisible(true);
    }//GEN-LAST:event_btnGoBackActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
        try {
            if (rs.next()) {
            String reflection1 = rs.getString("reflection").trim();
            
            String fName1 = rs.getString("firstName");
            String lName1 = rs.getString("lastName");
            String startDate1 = rs.getString("startDate");
            String endDate1 = rs.getString("endDate");
            String pName1 = rs.getString("projectName");
            int creativity1 = rs.getInt("creativity");
            int action1 = (rs.getInt("action"));
            int service1 = (rs.getInt("service"));
            String objective1 = rs.getString("objective");
            String hours1 = rs.getString("hours");
            String id1 = rs.getString("studentID");
            
            String firstName1 = fName1.trim();
            String lastName1 = lName1.trim();
            String newID1 = id1.trim();
            String newCreativity1 = null;
            String newAction1 = null;
            String newService1 = null;
            if (creativity1 == 0)
                newCreativity1 = "no";
            else
                newCreativity1 = "yes";
            if (action1 == 0)
                newAction1 = "no";
            else
                newAction1 = "yes";
            if (service1 == 0) 
                newService1 = "no";
            else 
                newService1 = "yes";
            
            
            String println1 = "Name: " + firstName1 + " " + lastName1 + "\n" +
                    "ID: " + newID1 + "\n" +
                    "Start date: " + startDate1 + "\n" + 
                    "End date: " + endDate1 + "\n" + 
                    "Project Name: " + pName1 + "\n" +
                    "creativity: " + newCreativity1 + "\n" +
                    "Action: " + newAction1 + "\n" +
                    "Service: " + newService1 + "\n" +
                    "Objective: " + objective1 + "\n" +
                    "Hours: " + hours1 + "\n" +
                    "Reflection: " + reflection1 + "\n";
            
            
            
            
            txtSummary.setText(println1);
            }
                
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousActionPerformed
        // TODO add your handling code here:
        try {
            if (rs.previous()) {
            
            String reflection2 = rs.getString("reflection").trim();
            
            String fName2 = rs.getString("firstName");
            String lName2 = rs.getString("lastName");
            String startDate2 = rs.getString("startDate");
            String endDate2 = rs.getString("endDate");
            String pName2 = rs.getString("projectName");
            int creativity2 = rs.getInt("creativity");
            int action2 = (rs.getInt("action"));
            int service2 = (rs.getInt("service"));
            String objective2 = rs.getString("objective");
            String hours2 = rs.getString("hours");
            String id2 = rs.getString("studentID");
            
            String firstName2 = fName2.trim();
            String lastName2 = lName2.trim();
            String newID2 = id2.trim();
            String newCreativity2 = null;
            String newAction2 = null;
            String newService2 = null;
            if (creativity2 == 0)
                newCreativity2 = "no";
            else
                newCreativity2 = "yes";
            if (action2 == 0)
                newAction2 = "no";
            else
                newAction2 = "yes";
            if (service2 == 0) 
                newService2 = "no";
            else 
                newService2 = "yes";
            
            
            String println2 = "Name: " + firstName2 + " " + lastName2 + "\n" +
                    "ID: " + newID2 + "\n" +
                    "Start date: " + startDate2 + "\n" + 
                    "End date: " + endDate2 + "\n" + 
                    "Project Name: " + pName2 + "\n" +
                    "creativity: " + newCreativity2 + "\n" +
                    "Action: " + newAction2 + "\n" +
                    "Service: " + newService2 + "\n" +
                    "Objective: " + objective2 + "\n" +
                    "Hours: " + hours2 + "\n" +
                    "Reflection: " + reflection2 + "\n";
            
            
            
            
            txtSummary.setText(println2);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_btnPreviousActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        try {
            String create = null;
            if (rs.getInt("creativity") == 0) {
                create = "no";
            } else {
                create = "yes";
            }
            String act = null;
            if (rs.getInt("action") == 0) {
                act = "no";
            } else {
                act = "yes";
            }
            String serve = null;
            if (rs.getInt("service") == 0) {
                serve = "no";
            } else { 
                serve = "yes";
            }
            String id = rs.getString("studentID").toUpperCase().trim();
            String[] ID = new String[1];
            ID[0] = id;
            fileSaver.main(ID);
            fileSaver writer = new fileSaver();
            writer.openFileForWriteAppend("Name: " + rs.getString("firstName").trim() + " " +
                    rs.getString("lastName").trim() + "\n" +
                    "ID: " + rs.getString("studentID").trim() + "\n" +
                    "Start Date: " + rs.getString("startDate").trim() + "\n" +
                    "End Date: " + rs.getString("endDate").trim() + "\n" +
                    "Project Name: " + rs.getString("projectName").trim() + "\n" +
                    "Creativity: " + create + "\n" +
                    "Action " + act + "\n" +
                    "Service: " + serve + "\n" + 
                    "Objective: " + rs.getString("objective").trim() + "\n" +
                    "Hours: " + rs.getString("hours").trim() + "\n" +
                    "Reflection: " + rs.getString("reflection").trim() + "\n" + "\n");
            
            
            JOptionPane.showMessageDialog(this, "Be sure to open the file 'casreport" + id + ".txt' in a Word Document for correct formatting");
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewStudentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewStudentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewStudentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewStudentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewStudentFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnGoBack;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrevious;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSelect;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList lstResults;
    private javax.swing.JPanel searchPanel;
    private javax.swing.JTextField txtLastName;
    public javax.swing.JTextField txtStudentID;
    private javax.swing.JTextArea txtSummary;
    private javax.swing.JPanel viewPanel;
    // End of variables declaration//GEN-END:variables
}
